// This source file is part of the Swift.org open source project
//
// Copyright (c) 2020 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See http://swift.org/LICENSE.txt for license information
// See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors

// Type aliases to drop the autogenerated prefix which is not really required since we're keeping the generated code in its own target.

public typealias CapabilitiesClient = Build_Bazel_Remote_Execution_V2_CapabilitiesClient
public typealias GetCapabilitiesRequest = Build_Bazel_Remote_Execution_V2_GetCapabilitiesRequest
public typealias ContentAddressableStorageClient = Build_Bazel_Remote_Execution_V2_ContentAddressableStorageClient
public typealias ServerCapabilities = Build_Bazel_Remote_Execution_V2_ServerCapabilities


public typealias FindMissingBlobsRequest = Build_Bazel_Remote_Execution_V2_FindMissingBlobsRequest
